import React from 'react';
import type { AiTool, Category, PromptCategory, Language, Prompt } from './types';

// FIX: Replaced JSX with React.createElement to be compatible with a .ts file.
// JSX is not supported in .ts files, and this was causing numerous compilation errors.
const IconPlaceholder = ({ className }: { className?: string }): React.ReactElement => (
  React.createElement('svg', {
    className: `w-10 h-10 ${className}`,
    fill: "none",
    viewBox: "0 0 24 24",
    stroke: "currentColor"
  },
    React.createElement('path', {
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: 2,
      d: "M13 10V3L4 14h7v7l9-11h-7z"
    })
  )
);

const commonIconProps = {
  className: "w-5 h-5",
  fill: "none",
  viewBox: "0 0 24 24",
  stroke: "currentColor",
  strokeWidth: 1.5,
};

// FIX: All icon components now accept props to allow className overrides.
// This resolves the React.cloneElement error in Sidebar.tsx.
interface IconProps {
  className?: string;
}

const IconCreative = (props: IconProps) => React.createElement('svg', { ...commonIconProps, ...props }, React.createElement('path', { strokeLinecap: 'round', strokeLinejoin: 'round', d: 'M9.53 16.122a3 3 0 00-5.78 1.128 2.25 2.25 0 01-2.4 2.245 4.5 4.5 0 008.4-2.245c0-.399-.078-.78-.22-1.128zm0 0a15.998 15.998 0 003.388-1.62m-5.043-.025a15.998 15.998 0 011.622-3.385m5.043.025a15.998 15.998 0 001.622-3.385m3.388 1.62a15.998 15.998 0 00-1.622-3.385m0 0a3 3 0 10-5.78 1.128 2.25 2.25 0 01-2.4 2.245 4.5 4.5 0 008.4-2.245c0-.399-.078-.78-.22-1.128zm0 0a15.998 15.998 0 00-3.388-1.62m-5.043-.025a15.998 15.998 0 01-1.622-3.385m5.043.025a15.998 15.998 0 01-1.622-3.385m3.388 1.62a15.998 15.998 0 011.622-3.385' }));
const IconWriting = (props: IconProps) => React.createElement('svg', { ...commonIconProps, ...props }, React.createElement('path', { strokeLinecap: 'round', strokeLinejoin: 'round', d: 'M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10' }));
const IconBusiness = (props: IconProps) => React.createElement('svg', { ...commonIconProps, ...props }, React.createElement('path', { strokeLinecap: 'round', strokeLinejoin: 'round', d: 'M2.25 18L9 11.25l4.306 4.307a11.95 11.95 0 015.814-5.519l2.74-1.22m0 0l-5.94-2.28m5.94 2.28l-2.28 5.941' }));
const IconCode = (props: IconProps) => React.createElement('svg', { ...commonIconProps, ...props }, React.createElement('path', { strokeLinecap: 'round', strokeLinejoin: 'round', d: 'M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5' }));
const IconGeneric = (props: IconProps) => React.createElement('svg', { ...commonIconProps, ...props }, React.createElement('path', { strokeLinecap: 'round', strokeLinejoin: 'round', d: 'M21 7.5l-9-5.25L3 7.5m18 0l-9 5.25m9-5.25v9l-9 5.25M3 7.5l9 5.25M3 7.5v9l9 5.25m0-9v9' }));
const IconSparkles = (props: IconProps) => React.createElement('svg', { ...commonIconProps, ...props }, React.createElement('path', { strokeLinecap: 'round', strokeLinejoin: 'round', d: 'M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.898 20.565l.223.874.223-.874a1.5 1.5 0 011.102-1.102l.874-.223-.874-.223a1.5 1.5 0 01-1.102-1.102l-.223-.874-.223.874a1.5 1.5 0 01-1.102 1.102l-.874.223.874.223a1.5 1.5 0 011.102 1.102z' }));

// New Icons
const IconWebsiteBuilder = (props: IconProps) => React.createElement('svg', { ...commonIconProps, ...props }, React.createElement('path', { strokeLinecap: 'round', strokeLinejoin: 'round', d: 'M12 21a9 9 0 00-9-9c-1.385 0-2.684.34-3.834.94M12 21a9 9 0 100-18 9 9 0 00-7.166 14.584M12 21v-3.75m0 3.75a9 9 0 005.166-14.584M12 17.25c-2.485 0-4.5-2.015-4.5-4.5s2.015-4.5 4.5-4.5 4.5 2.015 4.5 4.5-2.015 4.5-4.5 4.5zm0-2.25a2.25 2.25 0 100-4.5 2.25 2.25 0 000 4.5z' }));
const IconAppBuilder = (props: IconProps) => React.createElement('svg', { ...commonIconProps, ...props }, React.createElement('path', { strokeLinecap: 'round', strokeLinejoin: 'round', d: 'M10.5 1.5H8.25A2.25 2.25 0 006 3.75v16.5a2.25 2.25 0 002.25 2.25h7.5A2.25 2.25 0 0018 20.25V3.75a2.25 2.25 0 00-2.25-2.25H13.5M10.5 1.5L11.25 3.75m-1.5-2.25L9.75 3.75m0 0L9 1.5m3 2.25l.75-2.25M12 13.5a3 3 0 11-6 0 3 3 0 016 0z' }));
const IconCloud = (props: IconProps) => React.createElement('svg', { ...commonIconProps, ...props }, React.createElement('path', { strokeLinecap: 'round', strokeLinejoin: 'round', d: 'M2.25 15a4.5 4.5 0 004.5 4.5H18a3.75 3.75 0 001.332-7.257 3 3 0 00-2.43-2.43A3.75 3.75 0 0013.5 4.5a4.5 4.5 0 00-4.5 4.5v.75m0-3a3.75 3.75 0 00-3.75 3.75M12 12.75a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75h-.01a.75.75 0 01-.75-.75V12.75zm-3 0a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75h-.01a.75.75 0 01-.75-.75V12.75zm6 0a.75.75 0 01.75-.75h.01a.75.75 0 01.75.75v.01a.75.75 0 01-.75.75h-.01a.75.75 0 01-.75-.75V12.75z' }));

// FIX: Add missing constants for the stock chart feature.
export const STOCK_TICKERS: { [key: string]: string } = {
    'GOOGL': 'Alphabet (Google)',
    'MSFT': 'Microsoft',
    'META': 'Meta Platforms',
    'AMZN': 'Amazon',
    'NVDA': 'NVIDIA'
};

export const MARKET_COMPANY_COLORS: { [key: string]: string } = {
    'GOOGL': '#4285F4',
    'MSFT': '#7FBA00',
    'META': '#0081FB',
    'AMZN': '#FF9900',
    'NVDA': '#76B900'
};

export const translations: { [key in Language]: { [key: string]: string } } = {
  en: {
    home: 'Home',
    mostPopular: 'Most Popular',
    compareTools: 'Compare Tools',
    english: 'English',
    burmese: 'Burmese',
    traditionalChinese: 'Traditional Chinese',
  },
  my: { // Burmese
    home: 'ပင်မ',
    mostPopular: 'လူကြိုက်အများဆုံး',
    compareTools: 'Tools နှိုင်းယှဉ်ရန်',
    english: 'အင်္ဂလိပ်',
    burmese: 'မြန်မာ',
    traditionalChinese: 'တရုတ် (ရိုးရာ)',
  },
  'zh-TW': { // Traditional Chinese
    home: '首頁',
    mostPopular: '最熱門',
    compareTools: '比較工具',
    english: '英文',
    burmese: '緬甸文',
    traditionalChinese: '繁體中文',
  }
};

export const MOST_POPULAR_TOOLS: AiTool[] = [
  {
    rank: 1,
    name: 'ChatGPT',
    logo: React.createElement(IconPlaceholder, { className: "text-green-400" }),
    description: 'A versatile conversational AI from OpenAI that can answer questions, write content, debug code, and much more. It has become a daily utility for millions.',
    pros: ['Extremely versatile', 'High-quality text generation', 'Large knowledge base', 'Free tier available'],
    cons: ['Knowledge cutoff (not always real-time)', 'Can sometimes provide incorrect info', 'Heavy demand can lead to slow responses'],
    pricing: 'Freemium',
    startingPrice: '$20/mo',
    totalUsers: '180M+',
    url: 'https://chat.openai.com/',
    baseScore: 9.9,
    bestFor: 'General productivity',
    pricingPlans: [
      { name: 'Free', price: '$0', features: ['GPT-3.5 access', 'Standard responses', 'Web, iOS & Android'] },
      { name: 'Plus', price: '$20/mo', features: ['GPT-4 access', 'DALL-E, Browsing, & more', 'Priority access'] },
    ],
    usageByNation: [
      { nation: 'USA', percentage: 25, flag: '🇺🇸' },
      { nation: 'India', percentage: 12, flag: '🇮🇳' },
      { nation: 'Brazil', percentage: 8, flag: '🇧🇷' },
      { nation: 'UK', percentage: 7, flag: '🇬🇧' },
    ]
  },
  {
    rank: 2,
    name: 'Google Gemini',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-400" }),
    description: 'Google\'s powerful multimodal AI model, integrated across Google products. It excels at understanding context, images, and providing real-time information.',
    pros: ['Access to real-time information', 'Multimodal capabilities (text, image, audio)', 'Deep integration with Google services', 'Generous free access'],
    cons: ['Still evolving, can have inconsistencies', 'Interface can be less intuitive than competitors', 'Data privacy concerns'],
    pricing: 'Freemium',
    startingPrice: '$19.99/mo',
    totalUsers: '1B+ (via Google)',
    url: 'https://gemini.google.com/',
    baseScore: 9.7,
    bestFor: 'Real-time search & multimodal tasks',
    pricingPlans: [
        { name: 'Gemini', price: '$0', features: ['Standard model access', 'Integrated with Google Apps', 'Real-time search'] },
        { name: 'Gemini Advanced', price: '$19.99/mo', features: ['Most capable model (Ultra 1.0)', '2TB Google One storage', 'Better integration'] },
    ],
    usageByNation: [
      { nation: 'India', percentage: 18, flag: '🇮🇳' },
      { nation: 'USA', percentage: 15, flag: '🇺🇸' },
      { nation: 'Brazil', percentage: 9, flag: '🇧🇷' },
      { nation: 'Indonesia', percentage: 6, flag: '🇮🇩' },
    ]
  },
  {
    rank: 3,
    name: 'DeepSeek',
    logo: React.createElement(IconPlaceholder, { className: "text-purple-400" }),
    description: 'An open-source large language model specializing in code and reasoning. It offers powerful capabilities for developers and researchers.',
    pros: ['Excellent coding capabilities', 'Open source model', 'Strong reasoning skills', 'Fast inference times'],
    cons: ['Less general knowledge than competitors', 'Requires technical expertise to deploy', 'Smaller community support'],
    pricing: 'Free',
    totalUsers: '1M+ (Developers)',
    url: 'https://www.deepseek.com/',
    baseScore: 9.3,
    bestFor: 'Coding & development',
    pricingPlans: [
        { name: 'Open Source', price: 'Free', features: ['Downloadable models', 'Community support', 'Self-hosting'] },
    ],
    usageByNation: [
      { nation: 'China', percentage: 35, flag: '🇨🇳' },
      { nation: 'USA', percentage: 20, flag: '🇺🇸' },
      { nation: 'India', percentage: 10, flag: '🇮🇳' },
      { nation: 'Germany', percentage: 7, flag: '🇩🇪' },
    ]
  },
  {
    rank: 4,
    name: 'Midjourney',
    logo: React.createElement(IconPlaceholder, { className: "text-indigo-400" }),
    description: 'A leading AI image generator known for its highly artistic and photorealistic outputs. It\'s the go-to tool for digital artists and creatives.',
    pros: ['Stunning, artistic image quality', 'Powerful control over style', 'Active and creative community', 'Frequent updates'],
    cons: ['Discord-based interface is unusual', 'No free trial available', 'Steeper learning curve for advanced features'],
    pricing: 'Paid',
    startingPrice: '$10/mo',
    totalUsers: '15M+',
    url: 'https://www.midjourney.com/',
    baseScore: 9.8,
    bestFor: 'AI art & image generation',
    pricingPlans: [
        { name: 'Basic Plan', price: '$10/mo', features: ['~200 images/month', 'General commercial terms', 'Access to member gallery'] },
        { name: 'Standard Plan', price: '$30/mo', features: ['Unlimited Relaxed generations', '15h Fast generations', 'Stealth Mode available'] },
    ],
    usageByNation: [
      { nation: 'USA', percentage: 28, flag: '🇺🇸' },
      { nation: 'Japan', percentage: 11, flag: '🇯🇵' },
      { nation: 'Germany', percentage: 9, flag: '🇩🇪' },
      { nation: 'France', percentage: 6, flag: '🇫🇷' },
    ]
  },
  {
    rank: 5,
    name: 'Grammarly',
    logo: React.createElement(IconPlaceholder, { className: "text-green-500" }),
    description: 'An AI-powered writing assistant that goes beyond grammar and spelling to help improve writing style, tone, and clarity across multiple platforms.',
    pros: ['Excellent grammar and style checking', 'Integrates everywhere (browser, desktop)', 'Provides clear, actionable suggestions', 'Tone detection is very useful'],
    cons: ['Not a content generator', 'Premium features can be expensive', 'Can sometimes be overly prescriptive'],
    pricing: 'Freemium',
    startingPrice: '$12/mo',
    totalUsers: '30M+',
    url: 'https://www.grammarly.com/',
    baseScore: 9.5,
    bestFor: 'Writing & proofreading',
    pricingPlans: [
        { name: 'Free', price: '$0', features: ['Basic grammar & spelling', 'Punctuation checks', 'Tone detection'] },
        { name: 'Premium', price: '$12/mo', features: ['Style & clarity improvements', 'Plagiarism detection', 'Advanced suggestions'] },
    ],
    usageByNation: [
      { nation: 'USA', percentage: 35, flag: '🇺🇸' },
      { nation: 'UK', percentage: 10, flag: '🇬🇧' },
      { nation: 'Canada', percentage: 8, flag: '🇨🇦' },
      { nation: 'Australia', percentage: 7, flag: '🇦🇺' },
    ]
  },
  {
    rank: 6,
    name: 'Canva AI',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-500" }),
    description: 'A suite of AI tools integrated into the popular Canva design platform, including Magic Write and a text-to-image generator, making design accessible to everyone.',
    pros: ['Extremely easy to use', 'Integrated into a full design suite', 'Generous free tier for basic features', 'Great for social media graphics'],
    cons: ['Less powerful than dedicated AI models', 'Output quality can be limited', 'Can feel template-driven'],
    pricing: 'Freemium',
    startingPrice: '$14.99/mo',
    totalUsers: '150M+',
    url: 'https://www.canva.com/ai-image-generator/',
    baseScore: 8.9,
    bestFor: 'Quick graphic design',
    pricingPlans: [
        { name: 'Free', price: '$0', features: ['Basic AI tools', 'Limited Magic Write uses', 'Many free templates'] },
        { name: 'Pro', price: '$14.99/mo', features: ['Expanded AI tool access', 'Brand Kit', 'More stock photos & assets'] },
    ],
    usageByNation: [
      { nation: 'USA', percentage: 22, flag: '🇺🇸' },
      { nation: 'Brazil', percentage: 11, flag: '🇧🇷' },
      { nation: 'India', percentage: 9, flag: '🇮🇳' },
      { nation: 'Philippines', percentage: 7, flag: '🇵🇭' },
    ]
  },
  {
    rank: 7,
    name: 'GitHub Copilot',
    logo: React.createElement(IconPlaceholder, { className: "text-gray-400" }),
    description: 'An AI pair programmer that suggests code and entire functions in real-time from your editor, dramatically speeding up the development process.',
    pros: ['Seamless editor integration (VS Code, etc.)', 'Context-aware code suggestions', 'Speeds up development significantly', 'Supports dozens of languages'],
    cons: ['Can suggest incorrect or insecure code', 'Requires a subscription', 'Raises code ownership questions'],
    pricing: 'Paid',
    startingPrice: '$10/mo',
    totalUsers: '1.5M+',
    url: 'https://github.com/features/copilot',
    baseScore: 9.9,
    bestFor: 'Software development',
    pricingPlans: [
        { name: 'Individual', price: '$10/mo', features: ['AI code completion', 'Chat in IDE', 'CLI assistance'] },
        { name: 'Business', price: '$19/user/mo', features: ['All Individual features', 'Org-wide policy management', 'IP indemnity'] },
    ],
    usageByNation: [
      { nation: 'USA', percentage: 40, flag: '🇺🇸' },
      { nation: 'Germany', percentage: 8, flag: '🇩🇪' },
      { nation: 'India', percentage: 7, flag: '🇮🇳' },
      { nation: 'UK', percentage: 6, flag: '🇬🇧' },
    ]
  },
  {
    rank: 8,
    name: 'Perplexity AI',
    logo: React.createElement(IconPlaceholder, { className: "text-orange-400" }),
    description: 'A conversational search engine that provides direct answers to questions with cited sources. It\'s a powerful tool for research and learning.',
    pros: ['Provides direct answers with citations', 'Excellent for research', 'User-friendly interface', 'Focus mode for specific sources'],
    cons: ['Less conversational than ChatGPT', 'Can be slow with complex queries', 'Pro features are costly'],
    pricing: 'Freemium',
    startingPrice: '$20/mo',
    totalUsers: '10M+',
    url: 'https://www.perplexity.ai/',
    baseScore: 9.6,
    bestFor: 'Research & learning',
    pricingPlans: [
        { name: 'Free', price: '$0', features: ['Quick Search', 'Standard AI models', 'Limited Pro searches'] },
        { name: 'Pro', price: '$20/mo', features: ['Unlimited Pro searches', 'GPT-4, Claude 3, & more', 'File uploads'] },
    ],
    usageByNation: [
      { nation: 'USA', percentage: 38, flag: '🇺🇸' },
      { nation: 'UK', percentage: 9, flag: '🇬🇧' },
      { nation: 'Canada', percentage: 7, flag: '🇨🇦' },
      { nation: 'India', percentage: 6, flag: '🇮🇳' },
    ]
  },
  {
    rank: 9,
    name: 'Suno AI',
    logo: React.createElement(IconPlaceholder, { className: "text-yellow-500" }),
    description: 'An AI music and song generator that creates impressive, full-length songs with vocals and lyrics from a simple text prompt.',
    pros: ['Generates full songs with vocals', 'Surprisingly high audio quality', 'Very easy to use', 'Generous free tier'],
    cons: ['Limited control over musical output', 'Ethical concerns about training data', 'Can produce generic results'],
    pricing: 'Freemium',
    startingPrice: '$8/mo',
    totalUsers: '10M+',
    url: 'https://www.suno.ai/',
    baseScore: 9.8,
    bestFor: 'AI song creation',
    pricingPlans: [
        { name: 'Free Plan', price: '$0', features: ['50 credits/day', 'Non-commercial use', 'Shared generation queue'] },
        { name: 'Pro Plan', price: '$8/mo', features: ['2,500 credits/month', 'General commercial terms', 'Priority generation'] },
    ],
    usageByNation: [
      { nation: 'USA', percentage: 30, flag: '🇺🇸' },
      { nation: 'Japan', percentage: 12, flag: '🇯🇵' },
      { nation: 'UK', percentage: 8, flag: '🇬🇧' },
      { nation: 'South Korea', percentage: 7, flag: '🇰🇷' },
    ]
  },
  {
    rank: 10,
    name: 'Notion AI',
    logo: React.createElement(IconPlaceholder, { className: "text-stone-400" }),
    description: 'AI writing and summarization features built directly into the popular Notion productivity app, enhancing notes, docs, and project management.',
    pros: ['Seamlessly integrated into Notion workflow', 'Great for summarizing notes and brainstorming', 'Simple and intuitive to use'],
    cons: ['Less powerful than dedicated writing tools', 'Requires a Notion subscription', 'Can be slow at times'],
    pricing: 'Paid',
    startingPrice: '$8/mo',
    totalUsers: '30M+ (Notion Users)',
    url: 'https://www.notion.so/product/ai',
    baseScore: 8.8,
    bestFor: 'Integrated productivity',
    pricingPlans: [
        { name: 'Add-on', price: '$8/user/mo', features: ['Integrated into Notion', 'Summarize, rewrite, brainstorm', 'Works across your workspace'] },
    ],
    usageByNation: [
      { nation: 'USA', percentage: 32, flag: '🇺🇸' },
      { nation: 'South Korea', percentage: 9, flag: '🇰🇷' },
      { nation: 'Japan', percentage: 8, flag: '🇯🇵' },
      { nation: 'Germany', percentage: 6, flag: '🇩🇪' },
    ]
  }
];

const newTools: AiTool[] = [
  {
    rank: 0,
    name: 'DALL-E 3',
    logo: React.createElement(IconPlaceholder, { className: "text-cyan-400" }),
    description: 'OpenAI\'s advanced image generation model integrated into ChatGPT Plus, known for its ability to understand complex prompts and generate highly detailed and coherent images.',
    pros: ['Excellent prompt understanding', 'Integrated with ChatGPT', 'High-quality and coherent images', 'Generates text within images accurately'],
    cons: ['Requires ChatGPT Plus subscription', 'Less artistic control than Midjourney', 'Content policies can be restrictive'],
    pricing: 'Paid',
    startingPrice: '$20/mo',
    totalUsers: '10M+',
    url: 'https://openai.com/dall-e-3',
    baseScore: 9.6,
    bestFor: 'Detailed prompt-based images',
    pricingPlans: [
        { name: 'Via ChatGPT Plus', price: '$20/mo', features: ['Integrated in ChatGPT', 'Access to GPT-4', 'Advanced Data Analysis'] },
    ],
    usageByNation: [
      { nation: 'USA', percentage: 30, flag: '🇺🇸' },
      { nation: 'Japan', percentage: 10, flag: '🇯🇵' },
      { nation: 'UK', percentage: 8, flag: '🇬🇧' },
      { nation: 'Canada', percentage: 6, flag: '🇨🇦' },
    ]
  },
  {
    rank: 0,
    name: 'Stable Diffusion',
    logo: React.createElement(IconPlaceholder, { className: "text-red-400" }),
    description: 'A powerful, open-source text-to-image model that allows for immense customization and control. It can be run locally or through various online services.',
    pros: ['Open source and highly customizable', 'Can be run locally for free', 'Large active community developing new models', 'Fine-grained control with extensions'],
    cons: ['Steep learning curve', 'Requires powerful hardware for local use', 'Default output can be less polished than competitors'],
    pricing: 'Free',
    totalUsers: '5M+',
    url: 'https://stability.ai/',
    baseScore: 9.4,
    bestFor: 'Customizable AI art',
  },
  {
    rank: 0,
    name: 'Sora',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-600" }),
    description: 'OpenAI\'s text-to-video model that can generate high-fidelity, minute-long videos from text instructions, creating complex scenes with multiple characters and specific motion.',
    pros: ['Generates high-resolution, long videos', 'Incredible realism and world simulation', 'Understands complex narrative prompts', 'Maintains character and style consistency'],
    cons: ['Not yet publicly available', 'Expected to be very resource-intensive', 'Potential for misuse is high'],
    pricing: 'Paid',
    totalUsers: 'N/A',
    url: 'https://openai.com/sora',
    baseScore: 9.9,
    bestFor: 'High-fidelity video generation',
  },
  {
    rank: 0,
    name: 'RunwayML',
    logo: React.createElement(IconPlaceholder, { className: "text-pink-400" }),
    description: 'A comprehensive AI video creation suite that offers text-to-video, image-to-video, and a host of other powerful video editing tools for creators.',
    pros: ['Full suite of video editing tools', 'Relatively accessible and easy to use', 'Multiple generation modes (text, image, etc.)', 'Good for short, creative clips'],
    cons: ['Video quality can be inconsistent', 'Limited to short clips (4-16 seconds)', 'Can be expensive for heavy use'],
    pricing: 'Freemium',
    startingPrice: '$12/user/mo',
    totalUsers: '3M+',
    url: 'https://runwayml.com/',
    baseScore: 9.2,
    bestFor: 'Creative video clips & editing',
  },
  {
    rank: 0,
    name: 'Pika',
    logo: React.createElement(IconPlaceholder, { className: "text-lime-400" }),
    description: 'An idea-to-video platform that makes it easy to create and edit videos using AI. Known for its user-friendly interface and artistic styles.',
    pros: ['Very easy to use', 'Good for stylistic and animated videos', 'Free tier is generous', 'Fast generation times'],
    cons: ['Limited to very short clips (3 seconds)', 'Lower realism compared to Sora', 'Fewer advanced editing features'],
    pricing: 'Freemium',
    startingPrice: '$8/mo',
    totalUsers: '5M+',
    url: 'https://pika.art/',
    baseScore: 9.0,
    bestFor: 'Quick and easy AI video creation',
  },
  {
    rank: 0,
    name: 'Udio',
    logo: React.createElement(IconPlaceholder, { className: "text-orange-500" }),
    description: 'An AI music creation tool that generates high-quality songs with vocals from text prompts, rivaling Suno in quality and versatility.',
    pros: ['Excellent vocal and audio quality', 'Can generate longer song segments', 'Good genre versatility', 'Generous free credits'],
    cons: ['Newer, community still growing', 'Web interface is in beta', 'Some inconsistencies in lyrical coherence'],
    pricing: 'Freemium',
    startingPrice: '$10/mo',
    totalUsers: '2M+',
    url: 'https://www.udio.com/',
    baseScore: 9.7,
    bestFor: 'AI song creation',
  },
    // New Placeholder Tools
  {
    rank: 0,
    name: 'NemesisForge AI',
    logo: React.createElement(IconPlaceholder, { className: "text-red-500" }),
    description: 'A powerful engine for creating dynamic NPC behavior and emergent, unscripted narratives in open-world games.',
    pros: ['Highly adaptive AI', 'Easy to integrate with major engines', 'Creates unique player experiences'],
    cons: ['Computationally intensive', 'Requires specialized scripting knowledge'],
    pricing: 'Paid',
    startingPrice: '$499/license',
    totalUsers: '5k+ (Studios)',
    url: 'https://example.com/nemesisforge',
    baseScore: 9.3,
    bestFor: 'Dynamic NPC Behavior',
  },
  {
    rank: 0,
    name: 'WorldSynth',
    logo: React.createElement(IconPlaceholder, { className: "text-green-500" }),
    description: 'Procedurally generates vast and detailed game worlds, from realistic landscapes to sprawling sci-fi cities.',
    pros: ['Saves thousands of hours of manual design', 'Highly customizable parameters', 'Supports various biomes and architectural styles'],
    cons: ['Can produce generic-looking areas', 'Large export file sizes'],
    pricing: 'Freemium',
    startingPrice: '$99/mo',
    totalUsers: '20k+ (Developers)',
    url: 'https://example.com/worldsynth',
    baseScore: 9.1,
    bestFor: 'Procedural Content Generation',
  },
  {
    rank: 0,
    name: 'ValuateIQ',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-500" }),
    description: 'AI-powered platform for hyper-accurate property valuations and predictive market trend analysis.',
    pros: ['95%+ valuation accuracy', 'Real-time market data', 'Generates detailed reports'],
    cons: ['Subscription is expensive', 'Limited coverage in rural areas'],
    pricing: 'Paid',
    startingPrice: '$150/mo',
    totalUsers: '15k+ (Agents)',
    url: 'https://example.com/valuateiq',
    baseScore: 9.4,
    bestFor: 'Property Valuation',
  },
  {
    rank: 0,
    name: 'RealtyBot',
    logo: React.createElement(IconPlaceholder, { className: "text-indigo-500" }),
    description: 'Automates lead qualification and client communication via chat, freeing up agents to focus on closing deals.',
    pros: ['24/7 lead engagement', 'Integrates with major CRMs', 'Customizable conversation flows'],
    cons: ['Can sound robotic', 'Struggles with very complex queries'],
    pricing: 'Freemium',
    startingPrice: '$49/mo',
    totalUsers: '30k+ (Agents)',
    url: 'https://example.com/realtybot',
    baseScore: 8.9,
    bestFor: 'Lead Generation',
  },
  {
    rank: 0,
    name: 'ForensicLens',
    logo: React.createElement(IconPlaceholder, { className: "text-gray-600" }),
    description: 'AI-driven image and video analysis for forensic investigations, capable of identifying objects, faces, and license plates in low-quality footage.',
    pros: ['Enhances low-resolution video', 'Fast data processing', 'Secure evidence chain of custody'],
    cons: ['High cost per license', 'Potential for algorithmic bias', 'Requires certified operators'],
    pricing: 'Paid',
    totalUsers: '1k+ (Agencies)',
    url: 'https://example.com/forensiclens',
    baseScore: 9.5,
    bestFor: 'Forensic Analysis',
  },
  {
    rank: 0,
    name: 'PredPol',
    logo: React.createElement(IconPlaceholder, { className: "text-slate-500" }),
    description: 'Predictive policing software that uses historical crime data to identify areas with a high risk of future criminal activity.',
    pros: ['Helps optimize patrol routes', 'Data-driven resource allocation', 'Can lead to crime reduction'],
    cons: ['Controversial, ethical concerns', 'Risk of reinforcing historical bias', 'Lacks transparency'],
    pricing: 'Paid',
    totalUsers: '500+ (Cities)',
    url: 'https://example.com/predpol',
    baseScore: 7.8,
    bestFor: 'Predictive Policing',
  },
  {
    rank: 0,
    name: 'PaperGazer',
    logo: React.createElement(IconPlaceholder, { className: "text-amber-600" }),
    description: 'An AI research assistant that can summarize, categorize, and discover relevant scientific literature from a vast database of academic papers.',
    pros: ['Drastically cuts down literature review time', 'Identifies cross-disciplinary connections', 'Generates annotated bibliographies'],
    cons: ['May misinterpret highly nuanced text', 'Subscription required for full database access'],
    pricing: 'Freemium',
    totalUsers: '100k+ (Researchers)',
    url: 'https://example.com/papergazer',
    baseScore: 9.6,
    bestFor: 'Literature Review',
  },
  {
    rank: 0,
    name: 'SimuLab',
    logo: React.createElement(IconPlaceholder, { className: "text-cyan-600" }),
    description: 'Simulates complex experiments in physics, chemistry, and biology, allowing researchers to test hypotheses virtually before committing to lab work.',
    pros: ['Reduces cost and time of physical experiments', 'Allows for testing of dangerous or impossible scenarios', 'High-fidelity models'],
    cons: ['Simulations are only as good as the input data', 'Requires powerful computing resources'],
    pricing: 'Paid',
    totalUsers: '10k+ (Labs)',
    url: 'https://example.com/simulab',
    baseScore: 9.2,
    bestFor: 'Experiment Simulation',
  },
  {
    rank: 0,
    name: 'DrugWeaver',
    logo: React.createElement(IconPlaceholder, { className: "text-purple-600" }),
    description: 'An AI platform for designing and testing novel drug compounds in silico, significantly accelerating the pre-clinical phase of drug discovery.',
    pros: ['Identifies promising drug candidates faster', 'Predicts potential side effects', 'Reduces reliance on animal testing'],
    cons: ['Extremely expensive', 'Requires deep domain expertise to operate'],
    pricing: 'Paid',
    totalUsers: '200+ (Pharma Co.)',
    url: 'https://example.com/drugweaver',
    baseScore: 9.8,
    bestFor: 'Drug Discovery',
  },
  {
    rank: 0,
    name: 'CRISPR.ai',
    logo: React.createElement(IconPlaceholder, { className: "text-teal-500" }),
    description: 'Optimizes gene editing experiments by predicting the most effective guide RNAs and experimental conditions using machine learning.',
    pros: ['Increases success rate of CRISPR experiments', 'Reduces off-target effects', 'Saves time and lab resources'],
    cons: ['Predictions are not 100% accurate', 'Focused solely on CRISPR workflows'],
    pricing: 'Freemium',
    totalUsers: '15k+ (Geneticists)',
    url: 'https://example.com/crisprai',
    baseScore: 9.5,
    bestFor: 'Gene Editing',
  },
  {
    rank: 0,
    name: 'Adobe Firefly',
    logo: React.createElement(IconPlaceholder, { className: "text-red-500" }),
    description: 'Adobe\'s family of creative generative AI models, deeply integrated into Photoshop, Illustrator, and other Creative Cloud apps for professional workflows.',
    pros: ['Seamless integration with Adobe workflow', 'Trained on licensed content (commercially safe)', 'High-quality, professional-grade output', 'Versatile features (image gen, text effects)'],
    cons: ['Requires Adobe Creative Cloud subscription', 'Can be less experimental than Midjourney', 'Content policies can be restrictive'],
    pricing: 'Paid',
    startingPrice: '$20.99/mo (Photoshop)',
    totalUsers: '5M+',
    url: 'https://www.adobe.com/sensei/generative-ai/firefly.html',
    baseScore: 9.5,
    bestFor: 'Professional designers & Adobe users',
    pricingPlans: [
        { name: 'Creative Cloud', price: 'Varies', features: ['Integrated in Photoshop, Illustrator, etc.', 'Generative credits included', 'Commercially safe'] },
    ],
    usageByNation: [
      { nation: 'USA', percentage: 40, flag: '🇺🇸' },
      { nation: 'Germany', percentage: 10, flag: '🇩🇪' },
      { nation: 'UK', percentage: 8, flag: '🇬🇧' },
      { nation: 'Japan', percentage: 7, flag: '🇯🇵' },
    ]
  },
  {
      rank: 0,
      name: 'Kittl',
      logo: React.createElement(IconPlaceholder, { className: "text-yellow-600" }),
      description: 'An intuitive design platform with advanced features like AI-powered text effects, mockups, and a vast library of templates and illustrations.',
      pros: ['Powerful vector editing tools in-browser', 'Advanced AI text-to-image and transformations', 'Huge library of high-quality templates', 'Great for merchandise design'],
      cons: ['Can have a steeper learning curve than Canva', 'Free tier is limited in commercial use', 'AI credits can be used up quickly'],
      pricing: 'Freemium',
      startingPrice: '$10/mo',
      totalUsers: '2M+',
      url: 'https://www.kittl.com/',
      baseScore: 9.0,
      bestFor: 'T-shirt design & branding',
      pricingPlans: [
          { name: 'Free', price: '$0', features: ['Limited projects', 'Non-commercial license', 'Watermarks'] },
          { name: 'Pro', price: '$10/mo', features: ['Unlimited projects', 'Commercial license', 'AI credits included'] },
      ],
      usageByNation: [
        { nation: 'USA', percentage: 35, flag: '🇺🇸' },
        { nation: 'UK', percentage: 15, flag: '🇬🇧' },
        { nation: 'Germany', percentage: 9, flag: '🇩🇪' },
        { nation: 'Canada', percentage: 6, flag: '🇨🇦' },
      ]
  },
  {
      rank: 0,
      name: 'Recraft AI',
      logo: React.createElement(IconPlaceholder, { className: "text-teal-500" }),
      description: 'A generative AI design tool that specializes in creating consistent style vector art, icons, and 3D illustrations from text prompts.',
      pros: ['Excellent for generating vector art (SVG)', 'Maintains consistent style across images', 'Good for brand assets and icons', 'Free to use for now'],
      cons: ['Newer tool, still evolving', 'UI can be complex for beginners', 'Raster image quality is average'],
      pricing: 'Freemium',
      totalUsers: '1M+',
      url: 'https://www.recraft.ai/',
      baseScore: 9.1,
      bestFor: 'Vector illustrations & icons',
// FIX: Removed duplicate 'pros' and 'cons' properties which were causing a compile error.
  },
  {
      rank: 0,
      name: 'Looka',
      logo: React.createElement(IconPlaceholder, { className: "text-purple-500" }),
      description: 'An AI-powered platform that helps you design a custom logo and build a brand identity, from business cards to social media templates.',
      pros: ['Very fast logo generation', 'Provides full branding kits with mockups', 'Easy to use for non-designers', 'Multiple high-res file formats'],
      cons: ['Less creative control than a human designer', 'Can produce generic-looking results', 'One-time purchase model can be pricey'],
      pricing: 'Paid',
      startingPrice: '$20 (one-time)',
      totalUsers: '10M+',
      url: 'https://looka.com/',
      baseScore: 8.8,
      bestFor: 'Logo design for startups',
// FIX: Removed duplicate 'pros' and 'cons' properties which were causing a compile error.
  },
  {
      rank: 0,
      name: 'Magnific AI',
      logo: React.createElement(IconPlaceholder, { className: "text-blue-300" }),
      description: 'A state-of-the-art AI upscaler and image enhancer that adds incredible detail to images, allowing for high-resolution transformations.',
      pros: ['Adds stunning, creative details', 'Powerful upscaling capabilities (up to 16x)', 'Great for fantasy/sci-fi art enhancement', 'High level of control over "creativity"'],
      cons: ['Expensive credit-based system', 'Can be slow to process', 'Not suitable for all types of images (e.g., portraits)'],
      pricing: 'Paid',
      startingPrice: '$39/mo',
      totalUsers: '500k+',
      url: 'https://magnific.ai/',
      baseScore: 9.3,
      bestFor: 'Image upscaling & enhancement',
// FIX: Removed duplicate 'pros' and 'cons' properties which were causing a compile error.
  },
  {
      rank: 0,
      name: 'AutoDraw',
      logo: React.createElement(IconPlaceholder, { className: "text-yellow-400" }),
      description: 'A simple web-based drawing tool from Google that uses machine learning to guess what you\'re trying to draw and replaces your scribble with a clean illustration.',
      pros: ['Extremely simple and fun to use', 'Completely free', 'Great for quick diagrams or icons', 'No sign-up required'],
      cons: ['Very basic feature set', 'Limited, consistent art style', 'Not suitable for professional design work'],
      pricing: 'Free',
      totalUsers: '20M+',
      url: 'https://www.autodraw.com/',
      baseScore: 8.5,
      bestFor: 'Quick sketches & ideation',
// FIX: Removed duplicate 'pros' and 'cons' properties which were causing a compile error.
  },
  // New Business Tools
  {
    rank: 0,
    name: 'Jasper',
    logo: React.createElement(IconPlaceholder, { className: "text-orange-500" }),
    description: 'An AI content platform that helps teams create high-quality marketing copy, blog posts, and social media content 10x faster.',
    pros: ['Excellent for long-form content', 'Brand voice and tone features', 'Integrates with SEO tools', 'Wide variety of templates'],
    cons: ['Can be expensive for individuals', 'Fact-checking is still required', 'UI can be complex'],
    pricing: 'Paid',
    startingPrice: '$39/mo',
    totalUsers: '1.5M+',
    url: 'https://www.jasper.ai/',
    baseScore: 9.6,
    bestFor: 'Marketing Content Creation',
    pricingPlans: [
        { name: 'Creator', price: '$39/mo', features: ['1 Brand Voice', '50+ templates', 'SEO Mode'] },
        { name: 'Pro', price: '$59/mo', features: ['3 Brand Voices', 'Collaboration tools', '10 Campaigns'] }
    ]
  },
  {
    rank: 0,
    name: 'Copy.ai',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-500" }),
    description: 'An AI-powered copywriter that generates marketing copy and other content for businesses. Great for brainstorming and overcoming writer\'s block.',
    pros: ['Generous free plan', 'Easy to use interface', 'Good for short-form copy (ads, social)', 'Supports multiple languages'],
    cons: ['Long-form content is weaker than competitors', 'Output can be generic', 'Fewer advanced features'],
    pricing: 'Freemium',
    startingPrice: '$36/mo',
    totalUsers: '10M+',
    url: 'https://www.copy.ai/',
    baseScore: 9.2,
    bestFor: 'Short-form Copywriting',
    pricingPlans: [
        { name: 'Free', price: '$0', features: ['2,000 words', 'Chat by Copy.ai', '1 User seat'] },
        { name: 'Pro', price: '$36/mo', features: ['Unlimited words', '20+ languages', 'API Access'] }
    ]
  },
  {
    rank: 0,
    name: 'SEMrush',
    logo: React.createElement(IconPlaceholder, { className: "text-orange-600" }),
    description: 'A comprehensive SEO and marketing toolkit with AI features to help with keyword research, content optimization, and competitive analysis.',
    pros: ['All-in-one SEO platform', 'Powerful data and analytics', 'AI Writing Assistant for optimization', 'Excellent for competitor analysis'],
    cons: ['Very expensive', 'Steep learning curve', 'AI features are not standalone'],
    pricing: 'Paid',
    startingPrice: '$129.95/mo',
    totalUsers: '10M+',
    url: 'https://www.semrush.com/',
    baseScore: 9.4,
    bestFor: 'SEO & Content Marketing',
     pricingPlans: [
        { name: 'Pro', price: '$129.95/mo', features: ['Keyword research', 'Competitor analysis', 'Site audit'] },
        { name: 'Guru', price: '$249.95/mo', features: ['Content Marketing Platform', 'Historical data', 'Looker Studio integration'] }
    ]
  },
  {
    rank: 0,
    name: 'HubSpot AI',
    logo: React.createElement(IconPlaceholder, { className: "text-orange-400" }),
    description: 'A suite of AI tools built into the HubSpot CRM platform to help with content creation, email marketing, and data analysis.',
    pros: ['Seamlessly integrated with HubSpot CRM', 'Covers the entire customer lifecycle', 'Good for automating marketing tasks', 'Free tools available'],
    cons: ['Most powerful features require expensive plans', 'Locked into the HubSpot ecosystem', 'AI is a feature, not the core product'],
    pricing: 'Freemium',
    startingPrice: '$800/mo (Pro)',
    totalUsers: '200k+ (Customers)',
    url: 'https://www.hubspot.com/artificial-intelligence',
    baseScore: 9.1,
    bestFor: 'Integrated CRM Marketing',
    pricingPlans: [
        { name: 'Free Tools', price: '$0', features: ['AI Content Assistant (limited)', 'AI Email Writer', 'ChatSpot'] },
        { name: 'Professional', price: '$800/mo', features: ['Full AI Assistant suite', 'Content Remix', 'Campaign Assistant'] }
    ]
  },
  {
    rank: 0,
    name: 'Zendesk AI',
    logo: React.createElement(IconPlaceholder, { className: "text-green-600" }),
    description: 'An AI-powered customer service solution that automates support, provides intelligent routing, and offers insights from customer conversations.',
    pros: ['Powerful automation and workflows', 'Advanced analytics and reporting', 'Can summarize tickets automatically', 'Scales with business growth'],
    cons: ['Expensive, especially for advanced AI', 'Complex setup process', 'Can feel bloated with features'],
    pricing: 'Paid',
    startingPrice: '$55/agent/mo',
    totalUsers: '170k+ (Customers)',
    url: 'https://www.zendesk.com/ai/',
    baseScore: 9.5,
    bestFor: 'Enterprise Customer Service',
    pricingPlans: [
        { name: 'Suite Team', price: '$55/agent/mo', features: ['Ticketing system', 'Messaging', 'Help Center'] },
        { name: 'Suite Growth', price: '$89/agent/mo', features: ['Advanced AI add-on available', 'Self-service portal', 'Customizable reporting'] }
    ]
  },
  {
    rank: 0,
    name: 'Intercom',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-600" }),
    description: 'A customer communications platform with a powerful AI chatbot ("Fin") that provides instant, accurate answers and resolves support tickets.',
    pros: ['Excellent AI chatbot (Fin)', 'Great for proactive and conversational support', 'Easy to use and set up', 'Combines support, marketing, and sales'],
    cons: ['Pricing can be confusing and expensive', 'Some features are locked behind higher tiers', 'Less customizable than Zendesk'],
    pricing: 'Paid',
    startingPrice: '$39/mo (Starter)',
    totalUsers: '25k+ (Customers)',
    url: 'https://www.intercom.com/',
    baseScore: 9.6,
    bestFor: 'Conversational AI Support',
    pricingPlans: [
        { name: 'Starter', price: '$39/mo', features: ['Basic chat & email', 'Shared inbox', 'Help Center'] },
        { name: 'Pro', price: 'Custom', features: ['Fin AI Chatbot', 'Automated workflows', 'Advanced reporting'] }
    ]
  },
  {
    rank: 0,
    name: 'Drift',
    logo: React.createElement(IconPlaceholder, { className: "text-stone-700" }),
    description: 'A conversational AI platform focused on connecting B2B businesses with buyers, offering chatbots for lead qualification and customer support.',
    pros: ['Great for B2B lead generation', 'Strong integration with sales platforms', 'Personalized real-time conversations', 'Good analytics'],
    cons: ['Primarily sales-focused', 'Very expensive', 'Support features are less robust than dedicated tools'],
    pricing: 'Paid',
    startingPrice: 'Custom',
    totalUsers: '5k+ (Customers)',
    url: 'https://www.drift.com/',
    baseScore: 8.9,
    bestFor: 'B2B Sales & Support Chat',
    pricingPlans: [
        { name: 'Premium', price: 'Custom', features: ['Live chat', 'Chatbots', 'Meeting scheduling'] },
        { name: 'Advanced', price: 'Custom', features: ['Advanced routing', 'AI-powered chatbots', 'Salesforce integration'] }
    ]
  },
  {
    rank: 0,
    name: 'Salesforce Service Cloud Einstein',
    logo: React.createElement(IconPlaceholder, { className: "text-sky-500" }),
    description: 'AI built into the Salesforce platform that provides service agents with predictions, recommendations, and automation for customer support.',
    pros: ['Deep integration with Salesforce CRM', 'Powerful predictive analytics', 'Automates case classification and routing', 'Highly customizable'],
    cons: ['Requires Salesforce ecosystem', 'Complex and requires certified developers', 'Very high total cost of ownership'],
    pricing: 'Paid',
    startingPrice: '$75/user/mo',
    totalUsers: '150k+ (Customers)',
    url: 'https://www.salesforce.com/products/service-cloud/features/einstein/',
    baseScore: 9.3,
    bestFor: 'Salesforce-centric Support',
    pricingPlans: [
        { name: 'Enterprise', price: '$150/user/mo', features: ['Case Management', 'Service Console', 'Einstein Article Recommendations'] },
        { name: 'Unlimited', price: '$300/user/mo', features: ['Einstein Bots', 'Einstein Case Classification', 'Full AI suite'] }
    ]
  },
  {
    rank: 0,
    name: 'Freshdesk',
    logo: React.createElement(IconPlaceholder, { className: "text-lime-600" }),
    description: 'An omnichannel customer service software with "Freddy AI" to help automate resolutions, assist agents, and provide self-service options.',
    pros: ['Good value for the price', 'User-friendly interface', 'Omnichannel support (email, phone, chat)', 'Generous free plan'],
    cons: ['AI features are less advanced than top competitors', 'Can be slow at times', 'Reporting could be more robust'],
    pricing: 'Freemium',
    startingPrice: '$15/agent/mo',
    totalUsers: '60k+ (Customers)',
    url: 'https://www.freshworks.com/freshdesk/',
    baseScore: 9.0,
    bestFor: 'SMB Customer Support',
    pricingPlans: [
        { name: 'Free', price: '$0', features: ['Up to 10 agents', 'Email & social ticketing', 'Knowledge base'] },
        { name: 'Growth', price: '$15/agent/mo', features: ['Automation', 'Collision detection', 'Freddy AI add-on'] }
    ]
  },
  {
    rank: 0,
    name: 'Fireflies.ai',
    logo: React.createElement(IconPlaceholder, { className: "text-red-500" }),
    description: 'An AI meeting assistant that records, transcribes, and summarizes your voice conversations from various web-conferencing platforms.',
    pros: ['Automates note-taking for meetings', 'Integrates with many calendars and CRMs', 'Searchable transcripts', 'Identifies action items and tasks'],
    cons: ['Transcription accuracy can vary', 'Free tier is limited', 'Privacy concerns for some users'],
    pricing: 'Freemium',
    startingPrice: '$10/user/mo',
    totalUsers: '10M+',
    url: 'https://fireflies.ai/',
    baseScore: 9.4,
    bestFor: 'Meeting Transcription & Summaries',
    pricingPlans: [
        { name: 'Free', price: '$0', features: ['Limited transcription credits', '800 mins of storage', 'Joins Zoom, GMeet, etc.'] },
        { name: 'Pro', price: '$10/user/mo', features: ['Unlimited transcription', '8,000 mins of storage', 'AI summaries'] }
    ]
  },
  {
    rank: 0,
    name: 'Slack AI',
    logo: React.createElement(IconPlaceholder, { className: "text-violet-500" }),
    description: 'AI features built into Slack that provide conversation summaries, channel recaps, and an intelligent search that answers questions.',
    pros: ['Seamlessly integrated into your workflow', 'Great for catching up on conversations', 'Natural language search is powerful', 'Saves time finding information'],
    cons: ['Requires a paid Slack plan', 'Still in early stages of rollout', 'Less powerful than standalone AI tools'],
    pricing: 'Paid',
    startingPrice: 'Included in paid plans',
    totalUsers: 'N/A (Slack feature)',
    url: 'https://slack.com/features/ai',
    baseScore: 9.0,
    bestFor: 'Team Communication Efficiency',
    pricingPlans: [
        { name: 'Pro', price: '$7.25/user/mo', features: ['Channel recaps', 'Thread summaries', 'Search answers (add-on)'] },
        { name: 'Business+', price: '$12.50/user/mo', features: ['All AI features included', 'Advanced analytics', 'SSO'] }
    ]
  },
  {
    rank: 0,
    name: 'ClickUp AI',
    logo: React.createElement(IconPlaceholder, { className: "text-fuchsia-500" }),
    description: 'A comprehensive AI assistant integrated into the ClickUp productivity platform to help with writing, summarizing, and generating ideas.',
    pros: ['All-in-one productivity tool', 'AI is role-based (marketing, dev, etc.)', 'Generates subtasks and project plans', 'Good value as an add-on'],
    cons: ['Requires using the ClickUp platform', 'Can be overwhelming due to many features', 'AI performance can be inconsistent'],
    pricing: 'Paid',
    startingPrice: '$5/user/mo (Add-on)',
    totalUsers: '8M+',
    url: 'https://clickup.com/ai',
    baseScore: 9.2,
    bestFor: 'AI-powered Project Management',
    pricingPlans: [
        { name: 'Add-on', price: '$5/member/mo', features: ['100+ AI tools', 'Summarize tasks & comments', 'Write with AI'] }
    ]
  },
  // New Music & Video Tools
  {
    rank: 0,
    name: 'AIVA',
    logo: React.createElement(IconPlaceholder, { className: "text-purple-400" }),
    description: 'An AI music composer that specializes in creating emotional and epic soundtracks for films, games, and commercials.',
    pros: ['High-quality orchestral scores', 'Good for classical and soundtrack music', 'Customizable style models', 'Download in various formats (MIDI, MP3)'],
    cons: ['Less effective for modern pop/electronic music', 'Free version has limitations on usage rights', 'Interface can be complex for beginners'],
    pricing: 'Freemium',
    startingPrice: '€11/mo',
    totalUsers: '500k+',
    url: 'https://www.aiva.ai/',
    baseScore: 8.8,
    bestFor: 'Soundtrack & classical music',
  },
  {
    rank: 0,
    name: 'Soundraw',
    logo: React.createElement(IconPlaceholder, { className: "text-sky-400" }),
    description: 'An AI music generator for creators, offering a vast library of royalty-free music that can be customized by mood, genre, and length.',
    pros: ['Extremely easy to use', 'Generates royalty-free music instantly', 'Great for background music for videos', 'Good customization options'],
    cons: ['Lacks vocal generation', 'Music can sometimes sound generic', 'Less control over specific melodies'],
    pricing: 'Freemium',
    startingPrice: '$16.99/mo',
    totalUsers: '1M+',
    url: 'https://soundraw.io/',
    baseScore: 9.1,
    bestFor: 'Royalty-free background music',
  },
  {
    rank: 0,
    name: 'Boomy',
    logo: React.createElement(IconPlaceholder, { className: "text-pink-500" }),
    description: 'Generate original songs with AI in seconds, and submit your tracks to major streaming platforms to earn royalties.',
    pros: ['Incredibly fast song generation', 'Ability to publish to Spotify, Apple Music, etc.', 'Fun and experimental', 'Simple interface'],
    cons: ['Music quality can be very hit-or-miss', 'Limited creative control', 'Royalty splits can be complex'],
    pricing: 'Freemium',
    startingPrice: '$9.99/mo',
    totalUsers: '3M+',
    url: 'https://boomy.com/',
    baseScore: 8.5,
    bestFor: 'Experimental song creation',
  },
  {
    rank: 0,
    name: 'Amper Music',
    logo: React.createElement(IconPlaceholder, { className: "text-gray-400" }),
    description: 'An AI music composition tool designed to help non-musicians create unique, royalty-free music for their content without any musical knowledge.',
    pros: ['Simple, intuitive interface', 'No musical skill required', 'Good for creating custom-length tracks', 'API available for developers'],
    cons: ['Acquired by Shutterstock, future is uncertain', 'Less flexible than newer tools', 'Limited genre selection'],
    pricing: 'Paid',
    startingPrice: 'Varies (part of Shutterstock)',
    totalUsers: '1M+',
    url: 'https://www.shutterstock.com/discover/amper-music',
    baseScore: 8.2,
    bestFor: 'Custom royalty-free tracks',
  },
  {
    rank: 0,
    name: 'Synthesia',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-700" }),
    description: 'An AI video generation platform that creates professional videos with realistic AI avatars and voiceovers in over 120 languages.',
    pros: ['High-quality, realistic AI avatars', 'Supports many languages and accents', 'Great for corporate training and marketing videos', 'Easy to update video content'],
    cons: ['Expensive for individual creators', 'Avatars can sometimes fall into the "uncanny valley"', 'Less suited for creative, artistic videos'],
    pricing: 'Paid',
    startingPrice: '$22/mo',
    totalUsers: '50k+ (Businesses)',
    url: 'https://www.synthesia.io/',
    baseScore: 9.4,
    bestFor: 'AI avatar corporate videos',
  },
  {
    rank: 0,
    name: 'HeyGen',
    logo: React.createElement(IconPlaceholder, { className: "text-indigo-600" }),
    description: 'Create engaging business videos with generative AI avatars and voice cloning. A strong competitor to Synthesia, known for its dynamic features.',
    pros: ['Excellent voice cloning capabilities', 'Wide variety of avatars and templates', 'Streaming avatar for live interactions', 'Good for personalized sales videos'],
    cons: ['Can be costly for high volume', 'Some avatar movements can look unnatural', 'Free plan is very limited'],
    pricing: 'Freemium',
    startingPrice: '$24/mo',
    totalUsers: '2M+',
    url: 'https://www.heygen.com/',
    baseScore: 9.3,
    bestFor: 'AI presenter videos',
  },
  {
    rank: 0,
    name: 'InVideo AI',
    logo: React.createElement(IconPlaceholder, { className: "text-orange-400" }),
    description: 'A text-to-video generator that transforms your ideas, scripts, or articles into videos using a vast library of stock footage, music, and voiceovers.',
    pros: ['Creates videos from a simple text prompt', 'Huge library of stock media', 'AI-powered scripting and scene selection', 'Very fast video creation process'],
    cons: ['Relies on stock footage, not AI-generated scenes', 'Less control over final visual output', 'Voiceovers can sound robotic'],
    pricing: 'Freemium',
    startingPrice: '$20/mo',
    totalUsers: '8M+',
    url: 'https://invideo.io/ai/',
    baseScore: 9.0,
    bestFor: 'Content-to-video creation',
  },
  {
    rank: 0,
    name: 'Pictory',
    logo: React.createElement(IconPlaceholder, { className: "text-red-600" }),
    description: 'An AI video maker that automatically creates short, highly-shareable branded videos from your long-form content like articles, webinars, and podcasts.',
    pros: ['Excellent for repurposing content', 'AI automatically finds highlights', 'Adds captions and branding automatically', 'Fast and efficient workflow'],
    cons: ['Dependent on existing content', 'Visuals are stock-based', 'Less suited for creating from scratch'],
    pricing: 'Free Trial',
    startingPrice: '$19/mo',
    totalUsers: '1.5M+',
    url: 'https://pictory.ai/',
    baseScore: 8.9,
    bestFor: 'Repurposing long-form content',
  },
    // New Technical Tools
  {
    rank: 0,
    name: 'Framer AI',
    logo: React.createElement(IconPlaceholder, { className: "text-purple-500" }),
    description: 'A professional design tool that uses AI to generate and iterate on website designs and layouts from simple text prompts.',
    pros: ['Generates full websites from prompts', 'Professional-grade design tool', 'Responsive design by default', 'No-code and low-code capabilities'],
    cons: ['Steeper learning curve than simple builders', 'Can be expensive', 'AI is still an assistant, not a full replacement'],
    pricing: 'Freemium',
    startingPrice: '$20/mo',
    totalUsers: '1M+',
    url: 'https://www.framer.com/ai',
    baseScore: 9.5,
    bestFor: 'Designers & Prototyping',
  },
  {
    rank: 0,
    name: 'Durable',
    logo: React.createElement(IconPlaceholder, { className: "text-gray-700" }),
    description: 'The world\'s fastest AI website builder, generating a complete business website with copy, images, and a contact form in seconds.',
    pros: ['Incredibly fast setup', 'Generates all content automatically', 'Includes CRM and invoicing tools', 'Very affordable'],
    cons: ['Limited design customization', 'Generated content can be generic', 'Less suitable for complex sites'],
    pricing: 'Paid',
    startingPrice: '$12/mo',
    totalUsers: '500k+',
    url: 'https://durable.co',
    baseScore: 9.1,
    bestFor: 'Small Business Websites',
  },
  {
    rank: 0,
    name: 'Wix ADI',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-500" }),
    description: 'Wix\'s Artificial Design Intelligence (ADI) creates a custom website for you based on a few simple questions, which you can then customize.',
    pros: ['Very easy to use', 'Part of the powerful Wix ecosystem', 'Good for beginners', 'Creates a solid foundation to customize'],
    cons: ['Less creative freedom than the standard Wix Editor', 'Can\'t switch templates easily', 'Can feel restrictive for designers'],
    pricing: 'Freemium',
    startingPrice: '$16/mo',
    totalUsers: '200M+ (Wix users)',
    url: 'https://www.wix.com/adi-website-builder',
    baseScore: 9.0,
    bestFor: 'Beginner-friendly sites',
  },
  {
    rank: 0,
    name: 'Hostinger AI Website Builder',
    logo: React.createElement(IconPlaceholder, { className: "text-purple-600" }),
    description: 'An all-in-one solution integrated with Hostinger\'s hosting that uses AI to generate a complete website from a brand description.',
    pros: ['Integrated with hosting', 'Very affordable', 'AI generates text and finds relevant images', 'Includes marketing and SEO tools'],
    cons: ['Less feature-rich than dedicated builders', 'Design options are somewhat limited', 'Tied to Hostinger\'s ecosystem'],
    pricing: 'Paid',
    startingPrice: '$2.99/mo',
    totalUsers: '2M+',
    url: 'https://www.hostinger.com/website-builder',
    baseScore: 8.8,
    bestFor: 'All-in-one hosting & site',
  },
  {
    rank: 0,
    name: 'Jimdo Dolphin',
    logo: React.createElement(IconPlaceholder, { className: "text-sky-500" }),
    description: 'An AI-driven website builder designed for small businesses and self-employed individuals, creating a professional site in under 3 minutes.',
    pros: ['Extremely simple and fast', 'Automatically pulls business info from Google', 'Legally compliant text generation (GDPR)', 'Mobile-friendly designs'],
    cons: ['Very limited customization', 'Fewer widgets and apps than competitors', 'Not ideal for scaling businesses'],
    pricing: 'Freemium',
    startingPrice: '$9/mo',
    totalUsers: '25M+',
    url: 'https://www.jimdo.com/',
    baseScore: 8.6,
    bestFor: 'Simple business card sites',
  },
  {
    rank: 0,
    name: 'Bookmark Aida',
    logo: React.createElement(IconPlaceholder, { className: "text-red-500" }),
    description: 'An AI Design Assistant (Aida) that builds a unique website based on your specific needs, learning and adapting as you provide more information.',
    pros: ['AI assistant provides design suggestions', 'Good for e-commerce and blogs', 'Includes business management tools', 'Focuses on creating a unique look'],
    cons: ['Interface can be a bit clunky', 'Free plan is very limited', 'AI suggestions can be hit-or-miss'],
    pricing: 'Paid',
    startingPrice: '$11.99/mo',
    totalUsers: '1M+',
    url: 'https://www.bookmark.com/',
    baseScore: 8.4,
    bestFor: 'AI-assisted design',
  },
  {
    rank: 0,
    name: 'Bubble.io',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-400" }),
    description: 'A powerful no-code platform for building digital products and web apps, now with AI integrations for workflow automation and content generation.',
    pros: ['Extremely powerful and flexible', 'Build complex, scalable apps', 'Large plugin marketplace', 'Active community'],
    cons: ['Very steep learning curve', 'Not for native mobile apps', 'Can become expensive with scale'],
    pricing: 'Freemium',
    startingPrice: '$29/mo',
    totalUsers: '2M+',
    url: 'https://bubble.io',
    baseScore: 9.6,
    bestFor: 'Complex Web Apps',
  },
  {
    rank: 0,
    name: 'Glide',
    logo: React.createElement(IconPlaceholder, { className: "text-green-400" }),
    description: 'Create powerful custom apps from your data in spreadsheets or databases, with AI features to help build and populate your application.',
    pros: ['Incredibly easy to use', 'Turns spreadsheets into apps in minutes', 'Excellent for internal tools and simple apps', 'Good looking, modern UI'],
    cons: ['Less customizable than Bubble', 'Not for highly complex logic', 'Can be limited by data source'],
    pricing: 'Freemium',
    startingPrice: '$25/mo',
    totalUsers: '500k+',
    url: 'https://www.glideapps.com/',
    baseScore: 9.3,
    bestFor: 'Data-driven Apps',
  },
  {
    rank: 0,
    name: 'Adalo',
    logo: React.createElement(IconPlaceholder, { className: "text-indigo-400" }),
    description: 'A no-code platform for building real native mobile apps (for iOS and Android) and web apps using a simple drag-and-drop interface.',
    pros: ['Builds true native mobile apps', 'Simple drag-and-drop interface', 'Good for building MVPs quickly', 'Flexible database integrations'],
    cons: ['Less powerful than Bubble for complex logic', 'Performance can be an issue for large apps', 'Design customization is limited'],
    pricing: 'Freemium',
    startingPrice: '$36/mo',
    totalUsers: '300k+',
    url: 'https://www.adalo.com/',
    baseScore: 9.0,
    bestFor: 'Native Mobile Apps',
  },
  {
    rank: 0,
    name: 'FlutterFlow AI Gen',
    logo: React.createElement(IconPlaceholder, { className: "text-sky-400" }),
    description: 'A low-code builder for native mobile apps that uses AI to generate code, pages, and themes from natural language prompts, speeding up development.',
    pros: ['Generates real Dart/Flutter code', 'Speeds up development drastically', 'Build high-performance native apps', 'Can export clean code'],
    cons: ['Requires some coding knowledge to fully utilize', 'Steep learning curve for beginners', 'AI features are an add-on'],
    pricing: 'Paid',
    startingPrice: '$30/mo',
    totalUsers: '700k+',
    url: 'https://flutterflow.io/',
    baseScore: 9.4,
    bestFor: 'Low-code Mobile Devs',
  },
  {
    rank: 0,
    name: 'Bildr',
    logo: React.createElement(IconPlaceholder, { className: "text-yellow-500" }),
    description: 'A visual development platform for building web apps and SaaS products that is highly flexible and now includes AI-powered pattern generation.',
    pros: ['Extremely flexible and powerful', 'Builds like React with visual components', 'No platform lock-in (export code)', 'Good for building complex UIs'],
    cons: ['Very steep learning curve', 'Less beginner-friendly than competitors', 'Smaller community'],
    pricing: 'Freemium',
    startingPrice: '$29/mo',
    totalUsers: '50k+',
    url: 'https://www.bildr.com/',
    baseScore: 9.1,
    bestFor: 'SaaS & Web App Devs',
  },
  {
    rank: 0,
    name: 'Softr',
    logo: React.createElement(IconPlaceholder, { className: "text-purple-400" }),
    description: 'The easiest way to build custom web apps and client portals from your Airtable or Google Sheets data, no code required.',
    pros: ['Extremely easy to set up', 'Perfect for portals, directories, and internal tools', 'Deep integration with Airtable', 'Responsive designs out of the box'],
    cons: ['Limited to data sources (Airtable/Google Sheets)', 'Not for complex, custom logic', 'Less design freedom'],
    pricing: 'Freemium',
    startingPrice: '$49/mo',
    totalUsers: '200k+',
    url: 'https://www.softr.io/',
    baseScore: 8.9,
    bestFor: 'Airtable/Sheets Apps',
  },
  {
    rank: 0,
    name: 'Amazon SageMaker',
    logo: React.createElement(IconPlaceholder, { className: "text-orange-500" }),
    description: 'A fully managed service from AWS that enables developers and data scientists to build, train, and deploy machine learning models at scale.',
    pros: ['Fully managed infrastructure', 'Comprehensive set of tools (Jupyter, etc.)', 'Deeply integrated with the AWS ecosystem', 'Highly scalable'],
    cons: ['Can be very expensive', 'Complex for beginners', 'Vendor lock-in with AWS'],
    pricing: 'Paid',
    startingPrice: 'Pay-as-you-go',
    totalUsers: '100k+ (Companies)',
    url: 'https://aws.amazon.com/sagemaker/',
    baseScore: 9.8,
    bestFor: 'Enterprise ML on AWS',
  },
  {
    rank: 0,
    name: 'Google Vertex AI',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-500" }),
    description: 'A unified ML platform from Google Cloud to help build, deploy, and scale ML models faster, with pre-trained APIs and custom tooling.',
    pros: ['Unified MLOps platform', 'Access to Google\'s state-of-the-art models (Gemini)', 'AutoML for beginners', 'Good for both data scientists and developers'],
    cons: ['Complex pricing structure', 'Documentation can be dense', 'Newer than some competitors'],
    pricing: 'Paid',
    startingPrice: 'Pay-as-you-go',
    totalUsers: '80k+ (Companies)',
    url: 'https://cloud.google.com/vertex-ai',
    baseScore: 9.7,
    bestFor: 'ML on Google Cloud',
  },
  {
    rank: 0,
    name: 'Microsoft Azure AI',
    logo: React.createElement(IconPlaceholder, { className: "text-sky-500" }),
    description: 'A portfolio of AI services on Azure, including machine learning, cognitive services (vision, speech), and conversational AI bots.',
    pros: ['Comprehensive suite of AI services', 'Strong enterprise focus', 'Excellent cognitive services APIs', 'Integrated with Microsoft products'],
    cons: ['Can be complex to navigate', 'Some services are less mature than competitors', 'Pricing can be hard to predict'],
    pricing: 'Paid',
    startingPrice: 'Pay-as-you-go',
    totalUsers: '95% of Fortune 500',
    url: 'https://azure.microsoft.com/en-us/solutions/ai/',
    baseScore: 9.6,
    bestFor: 'Enterprise AI on Azure',
  },
  {
    rank: 0,
    name: 'IBM Watson',
    logo: React.createElement(IconPlaceholder, { className: "text-blue-700" }),
    description: 'A suite of enterprise-ready AI services, applications, and tooling from IBM, known for its natural language processing capabilities.',
    pros: ['Pioneer in enterprise AI', 'Strong in NLP and conversational AI', 'Focus on trust and transparency', 'Available on any cloud'],
    cons: ['Perceived as more expensive', 'Less "hyped" than other cloud providers', 'Interface can feel dated'],
    pricing: 'Paid',
    startingPrice: 'Varies',
    totalUsers: '100M+ (Users)',
    url: 'https://www.ibm.com/watson',
    baseScore: 9.2,
    bestFor: 'Enterprise NLP & Chatbots',
  },
  {
    rank: 0,
    name: 'Oracle Cloud AI',
    logo: React.createElement(IconPlaceholder, { className: "text-red-600" }),
    description: 'A set of AI and machine learning services on Oracle Cloud Infrastructure (OCI) designed for enterprise data and applications.',
    pros: ['Integrated with Oracle databases and apps', 'Competitive pricing', 'Good for data-centric AI tasks', 'Pre-built AI services for business'],
    cons: ['Smaller market share than AWS/Azure/GCP', 'Less community support and documentation', 'Still building out its full feature set'],
    pricing: 'Paid',
    startingPrice: 'Pay-as-you-go',
    totalUsers: '430k+ (Customers)',
    url: 'https://www.oracle.com/artificial-intelligence/',
    baseScore: 8.8,
    bestFor: 'Oracle-centric Enterprises',
  },
  {
    rank: 0,
    name: 'Snowflake Cortex',
    logo: React.createElement(IconPlaceholder, { className: "text-cyan-500" }),
    description: 'A fully managed service that provides access to LLMs and AI models directly within the Snowflake Data Cloud, with simple SQL/Python functions.',
    pros: ['AI functions run where your data lives (no data movement)', 'Simple SQL/Python functions to access AI', 'Serverless and cost-effective', 'Focus on data security and governance'],
    cons: ['New service, still evolving', 'Tied to the Snowflake ecosystem', 'Limited model choice compared to major clouds'],
    pricing: 'Paid',
    startingPrice: 'Pay-per-use',
    totalUsers: '9k+ (Customers)',
    url: 'https://www.snowflake.com/en/data-cloud/cortex/',
    baseScore: 9.4,
    bestFor: 'AI on Snowflake Data',
  }
];

const ALL_TOOLS = [...MOST_POPULAR_TOOLS, ...newTools];

const getTools = (toolNames: string[]): AiTool[] => {
    return toolNames
        .map(name => ALL_TOOLS.find(tool => tool.name === name))
        .filter((tool): tool is AiTool => tool !== undefined)
        .sort((a, b) => b.baseScore - a.baseScore)
        .map((tool, index) => ({ ...tool, rank: index + 1 }));
};


// FIX: Added complete CATEGORIES array, which was previously malformed and incomplete.
export const CATEGORIES: Category[] = [
  // New & Trending Category
  {
    name: 'New & Trending',
    slug: 'new-and-trending',
    metaTitle: 'New & Trending AI Tools | Hottest Releases of 2024',
    metaDescription: 'Stay ahead of the curve with our curated list of the newest and most exciting AI tools. Discover the latest breakthroughs in text-to-video, music generation, and more.',
    icon: React.createElement(IconSparkles),
    tools: getTools(['Sora', 'Udio', 'Pika', 'Magnific AI', 'Perplexity AI', 'HeyGen', 'RunwayML', 'Durable', 'Fireflies.ai', 'Recraft AI']),
  },
  // Creative Tools
  {
    name: 'Graphic Design',
    slug: 'graphic-design',
    metaTitle: 'Top 10 AI Graphic Design Tools | 2024 Review',
    metaDescription: 'Unleash your creativity with the top 10 AI graphic design tools of 2024. Our expert reviews cover Midjourney, Adobe Firefly, DALL-E 3, and more to help you create stunning visuals.',
    icon: React.createElement(IconCreative),
    tools: getTools(['Midjourney', 'DALL-E 3', 'Adobe Firefly', 'Stable Diffusion', 'Magnific AI', 'Recraft AI', 'Kittl', 'Canva AI', 'Looka', 'AutoDraw']),
  },
  {
    name: 'AI Writing',
    slug: 'ai-writing',
    metaTitle: 'Top AI Writing Assistants | 2024 Comparison',
    metaDescription: 'Find the best AI writing assistant. We review and rank top tools like ChatGPT, Grammarly, and Notion AI to improve your writing, productivity, and content creation.',
    icon: React.createElement(IconWriting),
    tools: getTools(['ChatGPT', 'Google Gemini', 'Grammarly', 'Notion AI', 'Jasper', 'Copy.ai']),
  },
  {
    name: 'Music Generation',
    slug: 'music-generation',
    metaTitle: 'Top 6 AI Music Generators | Create Your Own Songs',
    metaDescription: 'Create original, royalty-free music with the power of AI. Discover the best 6 AI music generators like Suno and AIVA for artists, content creators, and hobbyists. No musical experience required.',
    icon: React.createElement(IconSparkles),
    tools: getTools(['Suno AI', 'Udio', 'Soundraw', 'AIVA', 'Boomy', 'Amper Music']),
  },
  {
    name: 'Video Generation',
    slug: 'video-generation',
    metaTitle: 'Top 7 AI Video Generators | Text-to-Video Tools 2024',
    metaDescription: 'Turn your ideas into videos with AI. We review the 7 best text-to-video AI tools, including Sora, Synthesia and RunwayML, for creating marketing content, social media clips, and AI avatar videos.',
    icon: React.createElement(IconGeneric),
    tools: getTools(['Sora', 'Synthesia', 'HeyGen', 'RunwayML', 'InVideo AI', 'Pika', 'Pictory']),
  },

  // Business Tools
  {
    name: 'Marketing & Content',
    slug: 'marketing-and-content',
    metaTitle: 'Top AI Marketing & Content Tools | Automate Your Growth',
    metaDescription: 'Supercharge your marketing and content creation with AI. Discover the best tools for copywriting, SEO, social media management, and campaign optimization.',
    icon: React.createElement(IconBusiness),
    tools: getTools(['Jasper', 'ChatGPT', 'Copy.ai', 'SEMrush', 'HubSpot AI', 'Canva AI']),
  },
  {
    name: 'Customer Support',
    slug: 'customer-support',
    metaTitle: 'Top AI Customer Support Tools | Enhance User Experience',
    metaDescription: 'Deliver exceptional customer service with AI chatbots, automated ticketing systems, and sentiment analysis tools.',
    icon: React.createElement(IconBusiness),
    tools: getTools(['Intercom', 'Zendesk AI', 'Salesforce Service Cloud Einstein', 'Freshdesk', 'ChatGPT', 'Drift']),
  },
  {
    name: 'Sales & CRM',
    slug: 'sales-and-crm',
    metaTitle: 'Top AI Sales & CRM Platforms | Boost Your Revenue',
    metaDescription: 'Enhance your sales process and customer relationships with AI-powered CRM tools. We review the best platforms for lead generation, sales automation, and customer insights.',
    icon: React.createElement(IconBusiness),
    tools: getTools(['HubSpot AI', 'Salesforce Service Cloud Einstein', 'Drift', 'Intercom']),
  },
  {
    name: 'Operations & Automation',
    slug: 'operations-and-automation',
    metaTitle: 'Top AI Tools for Operations & Automation | Work Smarter',
    metaDescription: 'Streamline your business operations and automate repetitive tasks with AI. Discover tools for meeting summaries, project management, and workflow automation.',
    icon: React.createElement(IconGeneric),
    tools: getTools(['Fireflies.ai', 'Slack AI', 'ClickUp AI', 'Notion AI']),
  },
  {
    name: 'Finance & Analytics',
    slug: 'finance-and-analytics',
    metaTitle: 'Top AI Finance & Analytics Tools | Data-Driven Insights',
    metaDescription: 'Leverage AI for financial analysis, business intelligence, and data-driven decision-making. Compare platforms that offer predictive analytics and reporting.',
    icon: React.createElement(IconBusiness),
    tools: getTools(['SEMrush', 'HubSpot AI', 'Salesforce Service Cloud Einstein']),
  },

  // Technical Tools
  {
    name: 'Code Generation',
    slug: 'code-generation',
    metaTitle: 'Top AI Coding Assistants | Write Code Faster',
    metaDescription: 'Accelerate your development workflow with AI-powered code completion, debugging, and generation tools.',
    icon: React.createElement(IconCode),
    tools: getTools(['GitHub Copilot', 'DeepSeek', 'ChatGPT']),
  },
  {
    name: 'Website Builder',
    slug: 'website-builder',
    metaTitle: 'Top AI Website Builders | Build a Site in Minutes',
    metaDescription: 'Discover the best AI website builders of 2024. We review tools like Framer AI and Durable that create stunning, professional websites in seconds.',
    icon: React.createElement(IconWebsiteBuilder),
    tools: getTools(['Framer AI', 'Durable', 'Wix ADI', 'Hostinger AI Website Builder', 'Jimdo Dolphin', 'Bookmark Aida']),
  },
  {
    name: 'App Builder',
    slug: 'app-builder',
    metaTitle: 'Top AI No-Code App Builders | Create Your Own App',
    metaDescription: 'Build powerful web and mobile apps without writing code. We review the best AI-powered no-code platforms like Bubble.io, Glide, and Adalo.',
    icon: React.createElement(IconAppBuilder),
    tools: getTools(['Bubble.io', 'FlutterFlow AI Gen', 'Glide', 'Bildr', 'Adalo', 'Softr']),
  },
  {
    name: 'Cloud Platforms',
    slug: 'cloud-platforms',
    metaTitle: 'Top AI Cloud Platforms | Enterprise Machine Learning',
    metaDescription: 'Compare the leading AI and ML platforms from AWS, Google, and Microsoft. Our guide covers Amazon SageMaker, Vertex AI, Azure AI, and more.',
    icon: React.createElement(IconCloud),
    tools: getTools(['Amazon SageMaker', 'Google Vertex AI', 'Microsoft Azure AI', 'Snowflake Cortex', 'IBM Watson', 'Oracle Cloud AI']),
  },
];

// FIX: Added missing PROMPTS_CATEGORIES export.
export const PROMPTS_CATEGORIES: PromptCategory[] = [
  {
    name: 'Marketing',
    slug: 'marketing',
    metaTitle: 'AI Prompts for Marketing | Top 5 AI',
    metaDescription: 'Boost your marketing campaigns with these powerful AI prompts for content creation, social media, and SEO.',
    prompts: [
      { id: 'mkt-1', title: 'Generate Ad Copy', description: 'Create compelling ad copy for a new product.', promptText: 'Write 5 different versions of ad copy for a new [product name] targeting [target audience]. Highlight its [key feature 1] and [key feature 2].' },
      { id: 'mkt-2', title: 'Brainstorm Blog Post Ideas', description: 'Get a list of blog post ideas for your niche.', promptText: 'Generate 10 blog post titles about [topic] for a [target audience] blog. Focus on topics that are informative and engaging.' },
      { id: 'mkt-3', title: 'Write a Social Media Post', description: 'Craft an engaging social media post to promote an event or article.', promptText: 'Write a social media post for [platform, e.g., LinkedIn, Twitter] to promote our upcoming webinar on [topic]. Include a call-to-action to register and use relevant hashtags.' },
      { id: 'mkt-4', title: 'Create a Video Script Outline', description: 'Outline a script for a short promotional video.', promptText: 'Create a 60-second video script outline for our new [product/service]. The video should have a hook, introduce the problem, present our solution, and have a clear call to action.' },
    ]
  },
  {
    name: 'Productivity',
    slug: 'productivity',
    metaTitle: 'AI Prompts for Productivity | Top 5 AI',
    metaDescription: 'Enhance your productivity with AI prompts for summarizing text, writing emails, and managing tasks.',
    prompts: [
        { id: 'prod-1', title: 'Summarize Text', description: 'Get a quick summary of a long article or document.', promptText: 'Summarize the following text in 3 bullet points, focusing on the key takeaways:\n\n[Paste text here]' },
        { id: 'prod-2', title: 'Draft a Professional Email', description: 'Quickly draft a professional email for any occasion.', promptText: 'Draft a professional email to [recipient] about [subject]. The tone should be [tone, e.g., formal, friendly]. My key message is that [your key message].' },
        { id: 'prod-3', title: 'Create a Meeting Agenda', description: 'Generate a structured agenda for an upcoming meeting.', promptText: 'Create a meeting agenda for a 1-hour meeting about [meeting topic]. The attendees are [list attendees/roles]. Key discussion points are [point 1], [point 2], and [point 3].' },
        { id: 'prod-4', title: 'Brainstorm Solutions', description: 'Use AI to brainstorm creative solutions to a problem.', promptText: 'Brainstorm 5 creative solutions for the problem of [describe the problem]. Consider unconventional approaches and think outside the box.' },
    ]
  },
];

// FIX: Added missing FAQ_DATA export for SEO schema.
export const FAQ_DATA = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
        {
            "@type": "Question",
            "name": "What is Top 5 AI?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "Top 5 AI is the leading destination for discovering, comparing, and reviewing the best artificial intelligence tools. We provide unbiased rankings and in-depth analysis to help you find the right AI solution for your needs."
            }
        },
        {
            "@type": "Question",
            "name": "How do you rank the AI tools?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "Our rankings are based on a comprehensive algorithm that considers user ratings, expert reviews, feature sets, ease of use, pricing, and overall market impact. We update our rankings regularly to reflect the latest developments in the AI industry."
            }
        },
        {
            "@type": "Question",
            "name": "Is Top 5 AI free to use?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "Yes, our website is completely free for all users. We believe everyone should have access to reliable information about AI tools."
            }
        }
    ]
};